# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis	
  url: redis://localhost:6379/1

development:
  adapter: redis	
  url: redis://localhost:6379/2

test:
  url: redis://localhost:6379/3
